// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIAAz_WbarBDJRC-X7sF-S48cjG8vVpUg',
    appId: '1:175514363636:web:a98968293d64a4a3f620a1',
    messagingSenderId: '175514363636',
    projectId: 'regaproject-c2cf7',
    authDomain: 'regaproject-c2cf7.firebaseapp.com',
    databaseURL: 'https://regaproject-c2cf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'regaproject-c2cf7.firebasestorage.app',
    measurementId: 'G-8XCP4BPZ79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQutosMProsu_tfKeRMZ6sO_0_shh22zI',
    appId: '1:175514363636:android:540845e826cb8888f620a1',
    messagingSenderId: '175514363636',
    projectId: 'regaproject-c2cf7',
    databaseURL: 'https://regaproject-c2cf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'regaproject-c2cf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGgqgNZV9cR6V62PcRLHr06xf1ixpbkQk',
    appId: '1:175514363636:ios:4b03494a9b6d727af620a1',
    messagingSenderId: '175514363636',
    projectId: 'regaproject-c2cf7',
    databaseURL: 'https://regaproject-c2cf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'regaproject-c2cf7.firebasestorage.app',
    iosClientId: '175514363636-714sbvv6d6mui86v75tn2sm9hkih0f55.apps.googleusercontent.com',
    iosBundleId: 'com.example.regaproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGgqgNZV9cR6V62PcRLHr06xf1ixpbkQk',
    appId: '1:175514363636:ios:4b03494a9b6d727af620a1',
    messagingSenderId: '175514363636',
    projectId: 'regaproject-c2cf7',
    databaseURL: 'https://regaproject-c2cf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'regaproject-c2cf7.firebasestorage.app',
    iosClientId: '175514363636-714sbvv6d6mui86v75tn2sm9hkih0f55.apps.googleusercontent.com',
    iosBundleId: 'com.example.regaproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIAAz_WbarBDJRC-X7sF-S48cjG8vVpUg',
    appId: '1:175514363636:web:a98968293d64a4a3f620a1',
    messagingSenderId: '175514363636',
    projectId: 'regaproject-c2cf7',
    authDomain: 'regaproject-c2cf7.firebaseapp.com',
    databaseURL: 'https://regaproject-c2cf7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'regaproject-c2cf7.firebasestorage.app',
    measurementId: 'G-8XCP4BPZ79',
  );
}
